---
- hosts: limesurvey
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## create directories
  #################################
  - name: create directory etc
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/etc"
      state: directory

  ##################################
  ## install LimeSurvey
  ##################################
  - name: install limesurvey
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/limesurvey
      src: https://download.limesurvey.org/latest-stable-release/limesurvey{{limesurvey_release}}.zip
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}

  ##################################
  ## configuration
  ##################################
  - name: upload db config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/limesurvey/application/config/config.php" src="templates/config.php" mode=0600

  - name: upload email config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/limesurvey/application/config/email.php" src="templates/email.php" mode=0600

  ######################
  ## initialise instance
  ######################
  - name: initialise instance
    become: yes
    become_user: "{{pac}}-{{user}}"
    # see https://manual.limesurvey.org/Installation_using_a_command_line_interface_(CLI)
    shell: |
        php console.php install {{admin_user_name}} {{admin_user_password}} {{admin_full_name}} {{admin_email}} || exit -1
        touch /home/pacs/{{pac}}/users/{{user}}/.ansible_initialised
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/limesurvey/application/commands"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_initialised"

  ########################
  ## setup the apache site
  ########################
  - name: check for htdocs-ssl directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    stat:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
    register: htdocs_exists

  - name: drop htdocs-ssl directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: absent
    when: htdocs_exists.stat.islnk is defined and htdocs_exists.stat.islnk == False

  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/limesurvey"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link
